version: "3"

services:
  app:
    image: nhwalton/poe-app:latest
    ports: ["80:80"]
    volumes: 
        - ./app:/opt
        - /app/node_modules
    depends_on:
        - flask-api
  flask-api:
    image: nhwalton/poe-api:latest
    ports: ["6000:6000"]
    restart: "unless-stopped"
