version: "3"

services:
  nginx:
    image: nhwalton/poe-app:latest
    ports: 
        - "80:80"
        - "443:443"
    volumes: 
        - ./app:/opt
        - /app/node_modules
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
    depends_on:
        - flask-api
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  flask-api:
    image: nhwalton/poe-api:latest
    ports: ["6000:6000"]
    restart: "unless-stopped"
  certbot:
    image: certbot/certbot
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
