version: "3"

services:
  nginx:
    image: nhwalton/poe-app:latest
    ports: 
        - "80:80"
        - "443:443"
    volumes: 
        - ./app:/opt
        - /app/node_modules
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
    depends_on:
        - flask-api
  flask-api:
    image: nhwalton/poe-api:latest
    ports: ["6000:6000"]
    restart: "unless-stopped"
  certbot:
    image: certbot/certbot
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
